### ISSUE TITLE
GPU out of memory error

### ISSUE THREAD

**Issue by Neoanarika** [neptune-ml/open-solution-data-science-bowl-2018#64]
Got this out of memory error when i ran `python  main.py -- prepare_metadata` locally on my machine. 

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCStorage.cu:58 

Any ideas how i might change the settings so that I can run the code on my local machine ?

**Comment by kamil-kaczmarek** [comment]
Hi @Neoanarika, 

1. Please paste entire error message.
2. What GPU do you have? How much memory?

In the `prepare_metadata` we use GPU when we [calculate clusters](https://github.com/neptune-ml/open-solution-data-science-bowl-2018/blob/master/preparation.py#L97) for the validation purposes. But this is just single image in the forward pass.

Quick fix is to run it on CPUs -> in the [vgg_extractor()](https://github.com/neptune-ml/open-solution-data-science-bowl-2018/blob/master/preparation.py#L117) comment out these two lines:
```python
if torch.cuda.is_available():
    model = model.cuda()
```

Best,
Kamil

**Comment by Neoanarika** [comment]
Actually i found out my setup with cuda was the problem. Thanks for the help 👍

**Comment by kamil-kaczmarek** [comment]
@Neoanarika nice! I'm closing this issue.
