### ISSUE TITLE
Stuck in epoch 0 

### ISSUE THREAD

**Issue by Neoanarika** [neptune-ml/open-solution-data-science-bowl-2018#65]
I ran the code locally using this command
`sudo python main.py -- train_evaluate_predict_pipeline --pipeline_name unet_multitask
`
and changed my neptune.yaml accordingly to the setup guide as well. 

but the code got stuck at epoch 0 even after running over night
```
2018-04-03 21-55-43 steps >>> starting training...
2018-04-03 21-55-43 steps >>> initial lr: 0.0001
2018-04-03 21-55-43 steps >>> epoch 0 ...

```
Has anyone experience this before ? If you have, could you pls share your experience on how you managed to tackle this problem.

**Comment by kamil-kaczmarek** [comment]
Hi @Neoanarika,

It is most likely because you run the code on CPU instead of GPU and you have just few cores available.

Please check these questions:
1. Did you observe any errors?
2. What do you see in `htop` and `nvidia-smi` if you run the code with CUDA?

Let me know about your hardware that you use for training, especially:
1. GPU and GPU memory
2. memory
3. number of available cores

Best,
KK

**Comment by Neoanarika** [comment]
Hi KK, 

Thanks for the reply. I didn't receive any errors. When i use htop and nvidia-smi i notice that both the CPU and GPU were idle aka only 0-20% usage. I am currently running on Titan Xp GPU with 12GB on memory and i9 CPU (20 cores)

Thanks,
Ming Liang

**Comment by Neoanarika** [comment]
After investigating,  I found the pause came from

`for batch_id, data in enumerate(batch_gen):`

in steps/pytorch/models.py. I am right now trying to understand what batch_gen does.

**Comment by kamil-kaczmarek** [comment]
Hey @Neoanarika,

In [fit()](https://github.com/neptune-ml/open-solution-data-science-bowl-2018/blob/master/steps/pytorch/models.py#L47) `batch_gen` is a pair of `batch_id` (int), `data` (4d tensor).

You may have stale operations. In the fit it may be connected with callbacks or [_fit_loop()](https://github.com/neptune-ml/open-solution-data-science-bowl-2018/blob/master/steps/pytorch/models.py#L73).

In the [neptune.yaml:45](https://github.com/neptune-ml/open-solution-data-science-bowl-2018/blob/master/neptune.yaml#L45), try to increase `num_workers` to 8.

Do you have other processes working on GPU?

Best,
Kamil

**Comment by Neoanarika** [comment]
Hi KK, 

I increase the num_workers to 8. There is not much change in the output. Nope no other GPU process. 

Regards,
Ming Liang

**Comment by Neoanarika** [comment]
Hi Kamil,  

I managed to solve it. Apparently it was due to the limit set by my docker environment that i was running the code in. By adding this flag --shm-size 8G, I was able to get my setup to work. Thanks for your help, you may consider this case closed. 

Regards,
Ming Liang

**Comment by kamil-kaczmarek** [comment]
Hi @Neoanarika, glad to hear that you solved the problem. Thanks for sharing this fix -> you live you learn ;-)

closing this.
