### ISSUE TITLE
[error] Project with key 'DSB' not found.

### ISSUE THREAD

**Issue by kirk86** [neptune-ml/open-solution-data-science-bowl-2018#72]
Executing the following command: 
`neptune send main.py --worker gcp-gpu-large --environment pytorch-0.2.0-gpu-py3 -- train_evaluate_predict_pipeline --pipeline_name unet_multitask` produces the above error

**Comment by kamil-kaczmarek** [comment]
hey @kirk86,

In neptune you can have as many projects as you want. Each project has `name` and `key` and in our case `key=DSB`. Do this:

1. log in to [neptune.ml](https://neptune.ml/),
2. when logged in, click on the `Projects` button (top left corner)
3. click button `New project`
4. name is `Data Science Bowl` and key is `DSB`, color is optional so pick you favorite ;-)

At this point project is created and you are ready to go!

Best,
Kamil

**Comment by kirk86** [comment]
@kamil-kaczmarek thanks!
