### ISSUE TITLE
Run mask r-cnn notebook on neptune and get submission but LB score is 0.why?

### ISSUE THREAD

**Issue by offlinecc** [neptune-ml/open-solution-data-science-bowl-2018#75]
Run mask r-cnn notebook on neptune and get submission, but LB score is 0.why?

**Comment by yipcma** [comment]
there's an issue with the submission format, it prints out a list where it should be space separated.

**Comment by kamil-kaczmarek** [comment]
Hey @offlinecc @yipcma what exactly is your error message?

**Comment by offlinecc** [comment]
@kamil-kaczmarek there is not a error message, just 0.000 LB score
